### ISSUE TITLE
support --multipleSchemaImports

### ISSUE THREAD

**Issue by lionelmoi** [eerohele/saxon-gradle#10]
I am using saxon Enterprise Edition to perform schema-aware transformation.

Because of the structure of my schemas I have to import them several times and therefore get the following kind of message:

```
Warning at xs:import on line 11 column 56 of relationships.xsd:
  The schema document at technical_data_structure.xsd is not being read because schema
  components for this namespace are already available. To force the schema document to be
  read, set --multipleSchemaImports:on
```
I do not think it is possible to set `--multipleSchemaImports:on` with saxon-gradle.

**Comment by eerohele** [comment]
You're right, it's not.

I'll need to go through the available options for the paid Saxon editions and add support for those in the plugin. Shouldn't be a big job.

**Comment by eerohele** [comment]
It looks like Saxon doesn't actually have a command-line option called `-multipleSchemaImports`.

Can you find anything in the [Saxon documentation](https://www.saxonica.com/html/documentation/using-xsl/commandline/) that would correspond with that option?

**Comment by eerohele** [comment]
Oh, maybe it's just undocumented…? Saxon does indeed seem to recognize `--multipleSchemaImports:on` (with two dashes).

**Comment by eerohele** [comment]
Looks like you can set it in the [Saxon configuration file](https://www.saxonica.com/html/documentation/configuration/configuration-file/config-xsd.html). Have you given that a go?

**Comment by lionelmoi** [comment]
The config file is ok when you have a specific config file for a transform, it gets more complicated when you have different configurations for different transforms...

I have tried it and it works, but setting the option from the plugin would be a plus in certain situation I think.

**Comment by eerohele** [comment]
I understand.

I think adding support for passing in options as described in the last paragraph [on this page](https://www.saxonica.com/html/documentation/configuration/config-interfaces/config-commandline.html) is the way to go.

**Comment by lionelmoi** [comment]
Yep, that would do the trick 😄

**Comment by eerohele** [comment]
0.5.0 adds support for the `multipleSchemaImports` option, among other things.

Can you give it a go and let me know whether it works for you?

**Comment by lionelmoi** [comment]
`multipleSchemaImports` works. I have not tested the others.

**Comment by eerohele** [comment]
Great, good to hear! I'll close this issue.
