### ISSUE TITLE
Add a Wiki

### ISSUE THREAD

**Issue by tofi86** [eerohele/saxon-gradle#13]
Hi,

is it possible to enable the Wiki function on this repo?

I'd love to contribute some usage examples.

Thanks for your work!

Best,
Tobias

**Comment by eerohele** [comment]
Certainly! I've enabled the wiki and would truly appreciate any content you might be able to contribute.

**Comment by tofi86** [comment]
Great, thanks!

Unfortunately I can neither view nor edit the wiki. I think you have to initiate it at least with an empty page.

**Comment by eerohele** [comment]
Apologies — I haven't used the wiki feature before. How about now?

**Comment by tofi86** [comment]
I can view it now, but I don't have permission to edit.

I think you have to disable the setting "Restrict editing to collaborators only" or make me a collaborator – your choice! ;-)

**Comment by eerohele** [comment]
Editing should now be open to anybody.

**Comment by tofi86** [comment]
Works! Thanks!

**Comment by tofi86** [comment]
Alright, I added some pages, examples and How-To's.

Any chance you could do a review in near future?

I'm not a gradle expert, probably there's better ways of writing specific code I used in the * How-To* section. Feel free to correct it!

**Comment by tofi86** [comment]
Oh, and could you probably write an example of how to use a Catalog file for DTD/Schema validation?
https://github.com/eerohele/saxon-gradle/wiki/catalog-usage

Unfortuantely I wasn't able to get it working. And your example code in the repo only shows how to use it for XSLT.

**Comment by eerohele** [comment]
Thank you for the contributions! I'm on vacation this week, but I'll try to take a look next week.
