### ISSUE TITLE
Is it possible to specify the Saxon-HE version being used?

### ISSUE THREAD

**Issue by tofi86** [eerohele/saxon-gradle#14]
Hi,

is it somehow possible to specify the Saxon-HE version being used for transformations?
The current version uses 9.8 but I'd like to use a specific 9.7 version.

Checking out an earlier release doesn't solve this, because the 9.7 version does not match my requirement.

Best,
Tobias

**Comment by tofi86** [comment]
Alright, I was able to do this with the following configuration:

```gradle
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath('net.sf.saxon:Saxon-HE:9.7.0-21'){
      force = true
    }
  }
}

plugins {
  id 'com.github.eerohele.saxon-gradle' version '0.6.0'
}

import com.github.eerohele.SaxonXsltTask

...
```

I tried that before, but without `force = true` it didn't work...

**Comment by eerohele** [comment]
Yes, adding the Saxon version you want into the buildscript classpath should do the trick. I didn't know about `force`, though — good find!
