### ISSUE TITLE
Please do not use dynamic dependency

### ISSUE THREAD

**Issue by nkutsche** [eerohele/saxon-gradle#16]
Hi,

I spent a lot of time today with a bad issue: my previously working build failed since today without changes on my side.

Reason was, that you are using `compile 'net.sf.saxon:Saxon-HE:+'` as dependency, Micheal Kay released a new version (9.9.0-1) since my last build and this version has conflicts with another plugin I use.

I think this [article explains](https://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/) good why we  shouldn't use dynamic versions.

On the other hand: thanks for the good working plugin!

**Comment by eerohele** [comment]
Many apologies for the inconvenience.

You're correct: using a dynamic dependency is a bad idea.

I've released version 0.7.0, which fixes the Saxon dependency to 9.8.0-14. Can you give it a go and let me know whether it fixes the issue for you?

**Comment by nkutsche** [comment]
Great! That was fast and exactly what I needed! Thanks a lot!

And don't worry. I didn't know about the possibility of dynamic dependencies in Gradle. That's why it was a bit tricky to find the reason for the failings. So I've also expanded my Gradle skills. :-)
