### ISSUE TITLE
Support for -init Saxon command line argument

### ISSUE THREAD

**Issue by dwcramer** [eerohele/saxon-gradle#17]
When accessing Saxon from the command line, there is an -init (as of Saxon 9.3): "-init:initializer | The value is the name of a user-supplied class that implements the interface Initializer; this initializer will be called during the initialization process, and may be used to set any options required on the Configuration programmatically." 
https://www.saxonica.com/html/documentation/using-xsl/commandline/

Is there a way to set this value via the gradle plugin?

**Comment by eerohele** [comment]
`initializer` should work. As in:

```gradle
xslt {
    stylesheet 'stylesheet.xsl'
    input 'input.xml'
    initializer 'foo.bar.Baz'
}
```

If not, it's a bug, in which case please let me know.

**Comment by dwcramer** [comment]
Thanks, that works and now I see that it was in the readme and I'd overlooked it.
