### ISSUE TITLE
Plugin incompatible with Gradle 7.x due to missing input declarations

### ISSUE THREAD

**Issue by dgeissl** [eerohele/saxon-gradle#30]
Gradle is complaining about missing input declarations as this will no longer be supported in Gradle 7 the plugin will become incompatible, These are the deprecation warnings gradle enterprise is printing out for a `com.github.eerohele.SaxonXsltTask`:

- Property 'advancedOptions' is not annotated with an input or output annotation.
- Property 'catalogManager' is not annotated with an input or output annotation.
- Property 'commonArguments' is not annotated with an input or output annotation.
- Property 'defaultOutputExtension' is not annotated with an input or output annotation.
- Property 'options' is not annotated with an input or output annotation.
- Property 'parameters' is not annotated with an input or output annotation.
- Property 'stylesheetParameters' is not annotated with an input or output annotation.

**Comment by eerohele** [comment]
Fixed in v0.9.0-beta4. See also https://github.com/eerohele/saxon-gradle/pull/32#issuecomment-907611071.
