### ISSUE TITLE
use in doLast method

### ISSUE THREAD

**Issue by tofi86** [eerohele/saxon-gradle#8]
Hi, I would like to call the `xslt` task from within another tasks `doLast` method to be able to change the input directory while iterating over testfiles and performing other tasks.

This does not seem to work at the moment, the xslt task just isn't being executed.
Do you have an idea why?

```gradle
task runTests(dependsOn: lessCompile) {

  // test this data
  currentTestDir = 'data1'

  // run the transformation and rendering
  doLast {

    // transform test_dev.xml to test_dev_prep.xml
    xslt {
      input file('test/' + currentTestDir + '/test_dev.xml')
      stylesheet file('xslt/prepare.xsl')
      output file('test/' + currentTestDir + '/test_dev_prep.xml')
    }

    exec {
      workingDir '.'
      commandLine 'cmd', ....
    }

    javaexec {
      classpath = buildscript.configurations.classpath
      main = '.....'
      args = ['-headless', '-f1', 'test/' + currentTestDir + '/test_dev_expected.pdf', '-f2', 'test/' + currentTestDir + '/test_dev.pdf']
    }
  }
}
```

The `exec` task fails because the output of the xslt task is missing.
If the runTests task depends on a single `xslt` task, it works well, but I loose the option to provide a specific directory to the `xslt` task because the task cannot be called with parameters.

Thanks!

**Comment by eerohele** [comment]
I haven't kept up with Gradle's recent developments, but it seems that executing a task in a `doLast` block [isn't officially supported](https://stackoverflow.com/questions/8979582/how-do-you-execute-a-built-in-gradle-task-in-a-dofirst-dolast-closure). So I'm not sure there's a way for me to modify the plugin so that your example will work. If there is, I don't know how.

Can you define `currentTestDir` outside of the `runTests` task?

**Comment by tofi86** [comment]
Okay, thanks.

Sure, I could define `currentTestDir` outside of the `runTests` task and it works, but this is just a break-down of my full task where I iterate over dozens of folders in the `test/` dir and `currentTestDir` is set programmatically by iteration and then different tasks are performed in every subdir.

Maybe my Gradle skills are just too bad to get this done :-(

**Comment by eerohele** [comment]
My Gradle skills certainly aren't anything to brag about, but one option is to do something like this:

```groovy
import com.github.eerohele.SaxonXsltTask

// The list of things (folders) you're iterating
def things = ['foo', 'bar', 'baz']

things.forEach { thing ->
    task "transform-${thing}"(type: SaxonXsltTask) {
        stylesheet 'my-stylesheet.xsl'
        input file("$thing-input.xml")
        output "build/$thing-output.xml"
    }

    task "test-${thing}"(dependsOn: "transform-${thing}") {
        // insert whatever the "test" task should actually do here
        doLast {
            println "Hello, $thing!"
        }
    }
}

task "test-all"(dependsOn: things.collect { "test-${it}" } )
```

Then:

```bash
$ gradle test-all
```

Of course, I don't know enough about what you're trying to do to know whether that'll actually work.

**Comment by tofi86** [comment]
thanks, that's probably a good way to go. I'll try it...

**Comment by tofi86** [comment]
works, thanks!

**Comment by eerohele** [comment]
Glad to hear it!
