### ISSUE TITLE
Seems to ignore parameter output

### ISSUE THREAD

**Issue by juangamnik** [eerohele/saxon-gradle#9]
I tried to change the output directory, but it seems to have no effect (it always writes to $buildDir):

```groovy
xslt {
    stylesheet "${projectDir}/src/main/resources/some-stylesheet.xsl"

    input fileTree(dir: "$buildDir/xmlinput", include: '*.xml')

    // Set Saxon configuration file
    config 'config/configuration.xml'

    output "$buildDir/transformed"
}
```

Am I doing something wrong?

**Comment by eerohele** [comment]
No, you're right, it doesn't seem to work correctly. I'll look into it.

**Comment by eerohele** [comment]
Version 0.4.1 of the plugin should fix the issue. Can you give it a try and let me know how it goes?

**Comment by juangamnik** [comment]
Works like a charm! Thx. You're lightning fast :)
